# configs/settings.yml
app:
  title: "SACCO Pro"
  environment: "development"

auth:
  provider: "built_in"
  otp_required: false

rbac:
  roles: ["Admin", "Risk", "Collections", "Finance", "Auditor", "Board"]
  page_patterns:
    Admin: ["*"]
    Risk: ["02*", "03*", "06*", "07*", "09*", "12*", "11A*", "14*"]
    Collections: ["13*", "13A*"]
    Finance: ["03*", "03A*", "05A*", "14*", "02*", "09*"]
    Auditor: ["05*", "05A*", "07*", "09*", "12*", "02*", "03*"]
    Board: ["01*", "14*", "05A*", "03A*"]

limits:
  single_employer_share_max: 0.25
  liquidity_ratio_min: 0.10
  par30_trigger_max: 0.15

notif:
  email:
    enabled: true
    from: "noreply@sacco.com"
  sms:
    provider: "africas_talking"

policy_engine:
  schedule_cron: "*/15 * * * *"
  actions: ["email", "sms", "flag"]

ecl:
  lookback_months: 36
  min_obs_for_pd: 12
  lgd_floors:
    secured: 0.25
    unsecured: 0.45
  macro_overlays: true

dividend:
  max_recommendation: 0.07
  par30_gate: 0.15
  liquidity_gate: 0.10

database:
  driver: "duckdb"
  path: "data/warehouse/sacco.duckdb"